name: cademetro

services:
  db:
    image: postgres:16-alpine
    container_name: cademetro-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - cademetro_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cademetro-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  cademetro_pg_data: